name: .NET Sdk

on:
  push:
    branches: [ main, 1.0.0beta ]
  pull_request:
    branches: [ main, 1.0.0beta ]

jobs:
  build:

    runs-on: windows-latest
    env:
      Solution_Name: CapyCSS.sln
      Test_Project_Path: CapybaraVS\CapyCSS.csproj
      Wap_Project_Directory: CapybaraVS
      Wap_Project_Path: CapybaraVS\CapyCSS.wapproj

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test
